Feature/order header
practicum-wd-brazil/pdv pull request #5
Opened 2022-12-29 10:13 UTC by FelipeDaCosta

Criei o bloco order e ajustei a estrutura da sessão de vendas.

2022-12-29 22:56 UTC, thiagopuntar reviewed
Se quiser dar uma olhada na responsividade também, ótimo!

2022-12-29 22:56 UTC, thiagopuntar commented on src/index.html
> +                  <button>-</button>
Adicione o svg ao invés de utilizar o caractere.

2022-12-29 22:56 UTC, thiagopuntar commented on src/index.html
> +          <hr class="order__hr" />
Tenta testar utilizar o border-bottom

2022-12-29 22:56 UTC, thiagopuntar commented on src/index.html
> +          <button class="order__button">Finalizar</button>
Além da classe order__button, acho que pode utilizar os estilos da classe button e sua classe modificadora success

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  width: 367px;
Eu tentaria trocar por flex-basis ou width em %

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  font-size: 16px;
Pode utilizar rem

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 24px;
line height em proporção. ex 1.5

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 18px;
font-size rem line-height proporção

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  height: 300px;
Tenta extrapolar o número de elementos e habilitar o overflow-y (para colocar o scroll);

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  font-weight: 700;
font-size lineheight

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 15px;
font-size line-height

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  width: 130px;
Tenta extrapolar o nome para ver o que acontece.

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 18px;
font-size line-height

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 19px;
font-size line-height

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  font-size: 16px;
rem

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  background-color: white;
utilizar variável do css

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +.order__total-values-bold {
talvez utilizar somente uma delas?

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 15px;
font-size - line-height

2022-12-29 22:56 UTC, thiagopuntar commented on src/styles/order.css
> +  line-height: 19px;
font-size line-height

2023-01-02 17:41 UTC, felipedcm commented on src/styles/order.css
> +  width: 130px;
![image](https://user-images.githubusercontent.com/12756107/210264111-ca01cbd1-651b-47a3-a667-7bc87fff6532.png)
Mantive assim pq achei que fica melhor do que usando ellipse.

2023-01-06 12:09 UTC, thiagopuntar requested changes
Salve Felipe, tudo bem?
Ficou ótimo meu amigo, parabéns pelo trabalho. Só 3 pequenos comentários e um outro detalhe.
Sua branch está tendo conflitos com a cohort2, isso é algo super normal. No último webinar eu fiz uma demo explicando sobre o comando git rebase que te ajuda a resolver esses problemas.
Dá uma olhadinha (foi bem no início do webinar) ou qualquer coisa me chama. Mas é preciso resolver os conflitos para podermos mergear.

2023-01-06 12:09 UTC, thiagopuntar commented on src/index.html
> +            <li class="order__item item">
Acho que já podemos remover esses <li> de exemplo e deixar somente o template.

2023-01-06 12:09 UTC, thiagopuntar commented on src/index.html
> +                  <img src="./images/minus_button.svg" alt="remover item" />
Acho que seria legal adicionar um button e a img por dentro ou a img como background-image do button. Falo isso porque como isso vai desempenhar uma ação, faz sentido ser um button.

2023-01-06 12:09 UTC, thiagopuntar commented on src/styles/order.css
> +@media screen and (max-width: 800px) {
Pode usar um 1200 de breakpoint, como não tem o tablet e mobile, acho que abaixo de 1200 a gente pode trabalhar com esse mobile pra ficar menos "achatado" o resumo ali do lado direito.

2023-01-12 15:09 UTC, thiagopuntar approved these changes

2023-01-12 15:09 UTC, merged