Cohort3/menu categorias
practicum-wd-brazil/pdv pull request #9
Opened 2023-01-22 14:42 UTC by Edu-Fortes

Menu das categorias para Desktop e Mobile.
![menu__360px](https://user-images.githubusercontent.com/46508709/213921785-08263c9f-b9a9-4bfd-b8cd-bb5832a95f3b.JPG)
![menu__1440px](https://user-images.githubusercontent.com/46508709/213921789-ba368fd3-2444-4b8e-a188-48f2a4548b91.JPG)

2023-01-24 22:16 UTC, thiagopuntar requested changes

2023-01-24 22:16 UTC, thiagopuntar commented on src/blocks/page/page.css
> +  background: linear-gradient(180deg, #0a2a34 0%, rgba(80, 138, 156, 0.2) 100%);
Adicione um atributo fixed no background em telas maiores, o comportamento do linear-gradient é começar a repetir assim que acabar o tamanho da tela.

2023-01-24 22:16 UTC, thiagopuntar commented on src/blocks/menu/menu.css
> +  margin: 2.5rem 1.3rem;
Esses elementos nas bordas do body geralmente dão um pouco de dor de cabeça pra gente setar margin (tanto no header quando no footer). Acho que você pode trocar essas margins (pelo menos as verticais) por um padding no container. No caso específico, reparei que ao a gente adicionar essa margin no elemento do top, acabou aumentando tamanho do body. Não acho que tenha necessidade da gente ter esse scroll por conta do margin.

2023-01-24 22:16 UTC, thiagopuntar commented on src/blocks/menu/__image/menu__image.css
> +  max-height: inherit;
max-height é uma prop que geralmente a gente quer evitar de utilizar. Ela pode causar uns comportamentos indesejados como por exemplo overflow. 
No caso, eu tirei as props rodando local e continuou a funcionar normalmente. Tente remover todos os max-heights pra ver como fica

2023-01-24 22:16 UTC, thiagopuntar commented on src/blocks/menu/__paragraph/menu__paragraph.css
> +  color: hsla(0, 0%, 67%, 1);
Excelente utilizar hsla, muito obrigado meu amigo.
Vamos tentar fazer algo a mais? Que tal isolar as cores em um css de theme como uma variável css?
Qualquer dúvida me fala

2023-01-24 22:16 UTC, thiagopuntar commented on src/index.html
> +        <li class="menu__item">
Senti falta de um button dentro desse li, só por conta do que representa esses menu semanticamente. Quando a gente clicar nos elementos, queremos desempenhar ações. Excelente role para um button.

2023-01-25 10:49 UTC, Edu-Fortes commented on src/blocks/page/page.css
> +  background: linear-gradient(180deg, #0a2a34 0%, rgba(80, 138, 156, 0.2) 100%);
Não me atentei a essa possibilidade. Testei colocando um container para criar rolagem de página e visualizei o problema de repetição do background.

2023-01-25 10:49 UTC, Edu-Fortes commented on src/index.html
> +        <li class="menu__item">
Perfeito. Faz mais sentido mesmo adicionar um button.

2023-01-25 10:49 UTC, Edu-Fortes commented on src/blocks/menu/__paragraph/menu__paragraph.css
> +  color: hsla(0, 0%, 67%, 1);
Nossa, sensacional trabalhar com variável nesse tipo de customização. Obrigado pelo apontamento, não havia pensado nessa possibilidade.

2023-01-25 10:49 UTC, Edu-Fortes commented on src/blocks/menu/__image/menu__image.css
> +  max-height: inherit;
Realmente tirando o max-height não latera a disposição. Mas estava querendo seguir o Figma e na versão mobile o ícone fica menor. Alterei utilizando um scale, me fale o que acha.

2023-01-25 10:49 UTC, Edu-Fortes commented on src/blocks/menu/menu.css
> +  margin: 2.5rem 1.3rem;
Concordo, ficou bem melhor aplicando as alterações apontadas.

2023-02-01 22:38 UTC, thiagopuntar reviewed
Fala Edu, ficou excelente o trabalho! Parabéns, desculpa pelo height, não tinha me atentado. Tenta fazer os testes que eu comentei e a gente já aprova na sequencia.

Ainda não revisei a do hover porque vou esperar mergear essa para ver como ficou por lá, blz?

2023-02-01 22:38 UTC, thiagopuntar commented on src/blocks/menu/__image/menu__image.css
> +  transform: scale(0.75);
Fala Edu, desculpa a demora! E desculpa sobre o height, não tinha reparado nessa questão que os ícones tinham outro tamanho no mobile. Acredito que você possa usar o height então, nesse caso que não tem uma proporção, pode ficar a vontade de usar o height em px para uma img. A gente só recomenda ter cautela de utilizar height e max-height em seções da página que pode acabar causando overflow, mas no caso de uma imagem acho que funciona de boa... Talvez, na verdade, só de setar um width na imagem, pelo aspect ratio natural, a height já acompanhe o tamanho setado na width. Tenta fazer o teste.
Acho que dessa forma é um pouco melhor que o transform.. O transform você vai utilizar ao selecionar a categoria, provavelmente.

2023-02-02 09:38 UTC, Edu-Fortes commented on src/blocks/menu/__image/menu__image.css
> +  transform: scale(0.75);
Opa Puntar, imagina da demora! Estávamos de férias. Fiz o teste utilizando o width para não precisar usar o height, mas não da muito certo por conta da proporção da batata frita, fica muito diferente em relação aos outros ícones. No final utilizei o height mesmo.  Removi o max-height da classe menu__item, esse não estava ajudando em nada.

2023-02-06 21:44 UTC, thiagopuntar approved these changes

2023-02-06 22:12 UTC, merged